name: geopoint_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.1.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.3
  json_theme: ^4.0.0
  flutter_markdown: ^0.6.13
  flutter_native_splash: ^2.2.14  
  # Google Maps
  google_maps_flutter: ^2.1.0  # Latest version of Google Maps for Flutter
  #Riverpod
  flutter_riverpod: ">=2.5.1"
  riverpod_annotation: ">=2.5.1"
  #Forms  
  flutter_form_builder: ">=7.7.0"
  form_builder_validators: ">=8.4.0"
  intl: ">=0.17.0"
  flex_color_scheme: ">=7.3.1"
  #Video player
  video_player: ^2.2.15
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  #firestore
  #cloud_firestore: ">=1.0.0"
  cloud_firestore: "^4.13.1"
  #firebase_auth: ">=1.0.0"
  firebase_auth: ^4.14.0
  #firebase_core: ">=1.0.0"
  firebase_core: ^2.22.0
  #firebase_ui_auth: ">=1.0.0"
  firebase_ui_auth: ^1.10.0

  # flutterfire
  #geoflutterfire: 3.0.0-nullsafety.4




  #freezed
  freezed_annotation: ">=2.4.1"
  json_annotation: ">=4.8.1"
  provider: ^6.1.1
  #logger
  logger: ">=1.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ">=2.5.1"
  freezed: ">=2.4.3"
  json_serializable: ">=6.7.1"

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
 